"""Project-specific metadata for the local runtime."""

from agents.models import ProjectSpec

PROJECT_CONTEXT = {'repo_name': 'Synthesis-Venice-PrivateAgents',
 'project_name': 'Shadow Treasury Desk',
 'track': 'Venice Private Agents',
 'pitch': 'A private reasoning desk that keeps sensitive treasury, governance, and '
          'grant analysis off public rails while still producing verifiable downstream '
          'actions.',
 'idea_titles': ['Confidential Treasury Copilot',
                 'Private Risk Desk',
                 'Private Octant Grant Scorer'],
 'architecture_summary': 'Sensitive inputs are routed through a private-analysis '
                         'module, while only redacted decisions, hashes, and '
                         'consequence proofs reach public logs. A policy contract '
                         'binds each private recommendation to a permitted action '
                         'envelope so the repo stays privacy-first and auditable.',
 'overlap_targets': ['SelfProtocol',
                     'Lido stETH Treasury',
                     'Uniswap Agentic Finance',
                     'ENS',
                     'Octant',
                     'MetaMask Delegations'],
 'primary_contract_name': 'PrivateDecisionRegistry',
 'primary_python_module': 'venice_private_desk',
 'category': 'privacy',
 'daily_budget_usd': 114,
 'per_action_budget_usd': 28,
 'cooldown_seconds': 900,
 'discovery_inputs': [{'name': 'private_inputs',
                       'description': 'Sensitive facts that must not leave the private '
                                      'rail.'},
                      {'name': 'policy_envelope',
                       'description': 'Allowlisted actions and maximum consequence '
                                      'bounds.'},
                      {'name': 'public_consequences',
                       'description': 'Redacted decisions and onchain digests.'},
                      {'name': 'receipts',
                       'description': 'Verification notes and consequence proofs.'}],
 'live_demo_steps': ['Copy .env.example to .env and fill the required keys.',
                     'Deploy the contract with forge script script/Deploy.s.sol '
                     '--broadcast for PrivateDecisionRegistry.',
                     'Run python3 scripts/run_agent.py to produce a dry run for '
                     'venice_private_desk.',
                     'Set LIVE_MODE=true and rerun python3 scripts/run_agent.py with '
                     'real credentials.',
                     'Run python3 scripts/render_submission.py and attach TxIDs plus '
                     'repo links.'],
 'partners': [{'name': 'Venice',
               'docs_url': 'https://docs.venice.ai/',
               'env_vars': ['VENICE_API_KEY',
                            'VENICE_CHAT_COMPLETIONS_URL',
                            'VENICE_MODEL'],
               'endpoint_env': 'VENICE_CHAT_COMPLETIONS_URL',
               'action_kind': 'rest_json',
               'purpose': 'Run private reasoning over sensitive inputs.'},
              {'name': 'SelfProtocol',
               'docs_url': 'https://docs.self.xyz/',
               'env_vars': ['SELF_PROTOCOL_API_KEY', 'SELF_VERIFICATION_URL'],
               'endpoint_env': 'SELF_VERIFICATION_URL',
               'action_kind': 'rest_json',
               'purpose': 'Gate sensitive actions behind privacy-preserving proofs.'},
              {'name': 'Lido',
               'docs_url': 'https://docs.lido.fi/',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Route staking yield through guarded treasury actions.'},
              {'name': 'Uniswap',
               'docs_url': 'https://developers.uniswap.org/',
               'env_vars': ['UNISWAP_API_KEY', 'UNISWAP_QUOTE_URL'],
               'endpoint_env': 'UNISWAP_QUOTE_URL',
               'action_kind': 'rest_json',
               'purpose': 'Quote swaps and bounded liquidity moves.'},
              {'name': 'ENS',
               'docs_url': 'https://docs.ens.domains/',
               'env_vars': ['ENS_NAME'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Publish human-readable coordination and identity receipts.'},
              {'name': 'Octant',
               'docs_url': 'https://octant.app/',
               'env_vars': ['OCTANT_SIGNAL_URL'],
               'endpoint_env': 'OCTANT_SIGNAL_URL',
               'action_kind': 'rest_json',
               'purpose': 'Publish scored public-goods signals and DPI artifacts.'},
              {'name': 'MetaMask Delegations',
               'docs_url': 'https://docs.metamask.io/delegation-toolkit/',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Enforce delegation scopes, expiries, and intent '
                          'envelopes.'}],
 'actions': [{'id': 'venice_private_analysis',
              'target': 'venice',
              'purpose': 'Use Venice for a bounded action in this repo.',
              'partner': 'Venice',
              'action_kind': 'rest_json',
              'max_amount_usd': 5,
              'priority': 100,
              'sensitivity': 'high',
              'notes': ['Call Venice only after a dry-run artifact exists.',
                        'Use https://docs.venice.ai/ for credential setup.']},
             {'id': 'selfprotocol_zk_verify',
              'target': 'selfprotocol',
              'purpose': 'Use SelfProtocol for a bounded action in this repo.',
              'partner': 'SelfProtocol',
              'action_kind': 'rest_json',
              'max_amount_usd': 3,
              'priority': 95,
              'sensitivity': 'high',
              'notes': ['Call SelfProtocol only after a dry-run artifact exists.',
                        'Use https://docs.self.xyz/ for credential setup.']},
             {'id': 'lido_yield_route',
              'target': 'lido',
              'purpose': 'Use Lido for a bounded action in this repo.',
              'partner': 'Lido',
              'action_kind': 'contract_call',
              'max_amount_usd': 200,
              'priority': 90,
              'sensitivity': 'medium',
              'notes': ['Call Lido only after a dry-run artifact exists.',
                        'Use https://docs.lido.fi/ for credential setup.']},
             {'id': 'uniswap_quote_route',
              'target': 'uniswap',
              'purpose': 'Use Uniswap for a bounded action in this repo.',
              'partner': 'Uniswap',
              'action_kind': 'rest_json',
              'max_amount_usd': 220,
              'priority': 85,
              'sensitivity': 'medium',
              'notes': ['Call Uniswap only after a dry-run artifact exists.',
                        'Use https://developers.uniswap.org/ for credential setup.']},
             {'id': 'ens_ens_publish',
              'target': 'ens',
              'purpose': 'Use ENS for a bounded action in this repo.',
              'partner': 'ENS',
              'action_kind': 'contract_call',
              'max_amount_usd': 5,
              'priority': 80,
              'sensitivity': 'low',
              'notes': ['Call ENS only after a dry-run artifact exists.',
                        'Use https://docs.ens.domains/ for credential setup.']},
             {'id': 'octant_signal_publish',
              'target': 'octant',
              'purpose': 'Use Octant for a bounded action in this repo.',
              'partner': 'Octant',
              'action_kind': 'rest_json',
              'max_amount_usd': 25,
              'priority': 75,
              'sensitivity': 'medium',
              'notes': ['Call Octant only after a dry-run artifact exists.',
                        'Use https://octant.app/ for credential setup.']},
             {'id': 'metamask_delegations_delegate_scope',
              'target': 'metamask_delegations',
              'purpose': 'Use MetaMask Delegations for a bounded action in this repo.',
              'partner': 'MetaMask Delegations',
              'action_kind': 'contract_call',
              'max_amount_usd': 2,
              'priority': 70,
              'sensitivity': 'high',
              'notes': ['Call MetaMask Delegations only after a dry-run artifact '
                        'exists.',
                        'Use https://docs.metamask.io/delegation-toolkit/ for '
                        'credential setup.']}]}


def build_project_spec() -> ProjectSpec:
    """Return the repository-specific project metadata."""
    return ProjectSpec.from_dict(PROJECT_CONTEXT)
